//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by NetChess.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_NETCHESS                    102
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_NETCHETYPE                  129
#define IDD_DIALOG_OPTIONS              131
#define IDB_BITMAP_BASE                 132
#define IDB_BITMAP_ROOK_WHITE           133
#define IDB_BITMAP_BISHOP_WHITE         134
#define IDB_BITMAP_KING_BLACK           135
#define IDB_BITMAP_KING_WHITE           136
#define IDB_BITMAP_KNIGHT_BLACK         137
#define IDB_BITMAP_KNIGHT_WHITE         138
#define IDB_BITMAP_PAWN_BLACK           139
#define IDB_BITMAP_PAWN_WHITE           140
#define IDB_BITMAP_QUEEN_BLACK          141
#define IDB_BITMAP_QUEEN_WHITE          142
#define IDB_BITMAP_ROOK_BLACK           143
#define IDB_BITMAP_BISHOP_BLACK         144
#define IDD_DIALOG_SERVER_INFO          145
#define IDD_DIALOG_MESSAGE              146
#define IDD_DIALOG_HISTORY              147
#define IDD_DIALOG_PICK_PIECE           148
#define IDI_ICON_MAINFRAME_OPPOSITE     149
#define IDR_SHELL_MENU                  150
#define IDD_DIALOG_PROPERTIES           177
#define IDD_DIALOG_ACCEPT               178
#define IDD_DIALOG_LOST_PIECE           179
#define IDD_DIALOG_DEMO_FEED            180
#define IDD_DISKS                       182
#define IDD_DIALOG_SCORE                185
#define IDD_DIALOG_NEW_SCORE            186
#define IDC_CHECK_WHITE_ON_TOP          1000
#define IDC_BUTTON_WHITE_COLOR          1001
#define IDC_BUTTON_BLACK_COLOR          1002
#define IDC_STATIC_WHITE                1003
#define IDC_STATIC_BLACK                1004
#define IDC_EDIT_PORT_NUMBER            1007
#define IDC_IPADDRESS                   1008
#define IDC_EDIT_MESSAGE                1009
#define IDC_EDIT_RECEIVE_MESSAGE        1010
#define IDC_EDIT_HISTORY                1011
#define IDC_STATIC_ROOT_WHITE           1013
#define IDC_STATIC_BITMAP_KNIGHT        1014
#define IDC_STATIC_BISHOP_WHITE         1015
#define IDC_STATIC_QUEEN_WHITE          1016
#define IDC_STATIC_KING_WHITE           1017
#define IDC_STATIC_PAWN_WHITE           1018
#define IDC_STATIC_ROOT_BLACK           1019
#define IDC_STATIC_KNIGHT_BLACK         1020
#define IDC_STATIC_BISHOP_BLACK         1021
#define IDC_STATIC_QUEEN_BLACK          1022
#define IDC_STATIC_KING_BLACK           1023
#define IDC_STATIC_PAWN_BLACK           1024
#define IDC_STATIC_STATUS               1025
#define IDC_STATIC_IP_ADDRESS           1026
#define IDC_STATIC_CLIENT_STATUS        1026
#define IDC_STATIC_EMPTY                1027
#define IDC_STATIC_PIECE_TYPE1          1028
#define IDC_STATIC_PIECE_TYPE2          1029
#define IDC_STATIC_PIECE_TYPE3          1030
#define IDC_RADIO_WHITE                 1032
#define IDC_RADIO_BLACK                 1033
#define IDC_STATIC_ACCEPT               1037
#define IDC_STATIC_W1                   1038
#define IDC_STATIC_W2                   1039
#define IDC_STATIC_W3                   1040
#define IDC_STATIC_W4                   1041
#define IDC_STATIC_W5                   1042
#define IDC_STATIC_W6                   1043
#define IDC_STATIC_W7                   1044
#define IDC_STATIC_W8                   1045
#define IDC_STATIC_W9                   1046
#define IDC_STATIC_W10                  1047
#define IDC_STATIC_W11                  1048
#define IDC_STATIC_W12                  1049
#define IDC_STATIC_W13                  1050
#define IDC_STATIC_W14                  1051
#define IDC_STATIC_W15                  1052
#define IDC_STATIC_W16                  1053
#define IDC_STATIC_B1                   1054
#define IDC_STATIC_B2                   1055
#define IDC_STATIC_B3                   1056
#define IDC_STATIC_B4                   1057
#define IDC_STATIC_B5                   1058
#define IDC_STATIC_B6                   1059
#define IDC_STATIC_B7                   1060
#define IDC_STATIC_B8                   1061
#define IDC_STATIC_B9                   1062
#define IDC_STATIC_B10                  1063
#define IDC_STATIC_B11                  1064
#define IDC_STATIC_B12                  1065
#define IDC_STATIC_B13                  1066
#define IDC_STATIC_B14                  1067
#define IDC_STATIC_B15                  1068
#define IDC_STATIC_B16                  1069
#define IDC_COMBO_FROM_LETTER           1076
#define IDC_COMBO_FROM_NUMBER           1077
#define IDC_COMBO_TO_LETTER             1078
#define IDC_COMBO_TO_NUMBER             1079
#define IDC_BUTTON_ADD                  1083
#define IDC_RADIO_TOSS                  1084
#define IDC_EDIT_DISKS                  1091
#define IDC_SLIDER1                     1093
#define IDC_RADIO_1                     1094
#define IDC_RADIO_3                     1095
#define IDC_RADIO_2                     1096
#define IDC_RADIO_4                     1097
#define IDC_RADIO_5                     1098
#define IDC_RADIO_6                     1099
#define IDC_RADIO_7                     1100
#define IDC_EDIT_GAME_LEVEL             1101
#define IDC_STATIC_RANK1                1108
#define IDC_STATIC_RANK2                1109
#define IDC_STATIC_RANK3                1110
#define IDC_STATIC__RANK4               1111
#define IDC_STATIC__RANK5               1112
#define IDC_STATIC__RANK6               1113
#define IDC_STATIC__RANK7               1114
#define IDC_STATIC__RANK8               1115
#define IDC_STATIC__RANK9               1116
#define IDC_STATIC__RANK10              1117
#define IDC_STATIC_NAME1                1118
#define IDC_STATIC_NAME2                1119
#define IDC_STATIC_NAME3                1120
#define IDC_STATIC_NAME4                1121
#define IDC_STATIC_NAME5                1122
#define IDC_STATIC__NAME6               1123
#define IDC_STATIC__NAME7               1124
#define IDC_STATIC__NAME8               1125
#define IDC_STATIC__NAME9               1126
#define IDC_STATIC__NAME10              1127
#define IDC_STATIC_SCORE1               1128
#define IDC_STATIC_SCORE2               1129
#define IDC_STATIC_SCORE3               1130
#define IDC_STATIC_SCORE4               1131
#define IDC_STATIC_SCORE5               1132
#define IDC_STATIC_SCORE6               1133
#define IDC_STATIC_SCORE7               1134
#define IDC_STATIC_SCORE8               1135
#define IDC_STATIC_SCORE9               1136
#define IDC_STATIC_SCORE10              1137
#define IDC_EDIT_NAME                   1138
#define IDC_EDIT_SCORE                  1139
#define ID_VIEW_HIDE                    32771
#define ID_EDIT_OPTIONS                 32772
#define ID_TOOLS_CLIENT                 32773
#define ID_TOOLS_SERVER                 32774
#define ID_TOOLS_SENDMESSAGE            32775
#define ID_TOOLS_HISTORY                32778
#define ID_VIEW_NUMBER                  32779
#define ID_VIEW_LETTER                  32780
#define ID_FILE_SAVEHISTORY             32781
#define ID_TOOLS_PLAYHISTORY            32782
#define ID_SHELL_CLOSE                  32783
#define ID_SHELL_VIEW                   32784
#define ID_VIEW_HISTORY                 32786
#define ID_TOOLS_WHITEONTOP             32787
#define ID_EDIT_MOVEFIRST               32792
#define ID_EDIT_MOVELAST                32793
#define ID_HELP_HOWTOPLAY               32799
#define ID_TOOLS_DISCONNECT             32800
#define ID_EDIT_PROPERTIES              32801
#define D_EDIT_PROPERTIES               32802
#define ID_TOOLS_RESIGN                 32804
#define ID_TOOLS_DRAW                   32805
#define ID_VIEW_LOSTPIECES              32806
#define ID_FILE_FEED                    32807
#define ID_TOOLS_LEARN                  32808
#define ID_EDIT_SETBOARD                32809
#define ID_EDIT_CHECKMOVE               32811
#define ID_EDIT_LEVEL                   32813
#define ID_EDIT_START                   32814
#define ID_EDIT_STOP                    32815
#define ID_EDIT_COLOR_SNAKECOLOR        32816
#define ID_EDIT_COLOR_FOODCOLOR         32817
#define ID_EDIT_COLOR_BACKGROUNDCOLOR   32818
#define ID_EDIT_COLOR_BARCOLOR          32819
#define ID_VIEW_SCORE                   32820

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        188
#define _APS_NEXT_COMMAND_VALUE         32821
#define _APS_NEXT_CONTROL_VALUE         1140
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
